import type { BuilderBadgeData } from '../types';

export const BUILDER_CLASSES = [
  'TERMINAL WIZARD',
  'PROMPT ENGINEER',
  'BYTE SORCERER',
  'CODE ALCHEMIST',
  'KERNEL ARCHITECT',
  'PIXEL ARTISAN',
  'FULLSTACK NINJA',
  'AI RESEARCHER',
  'CYBER DECKER',
  'PROTOCOL HACKER',
];

export const ROLES = [
  'SOFTWARE DEVELOPMENT',
  'AI & MACHINE LEARNING',
  'WEB3 & PROTOCOLS',
  'CREATIVE DIRECTION',
  'SYSTEMS ENGINEERING',
  'UI/UX ARCHITECTURE',
  'GAME DEVELOPMENT',
  'DATA SCIENCE',
];

export const BEACH_ITEMS_PRESETS = [
  { icon: '🥥', label: 'COCONUT' },
  { icon: '🛺', label: 'AUTO RICKSHAW' },
  { icon: '🚂', label: 'TRAIN PASS' },
  { icon: '💻', label: 'VS CODE' },
  { icon: '🎧', label: 'LO-FI BEATS' },
  { icon: '🌴', label: 'PALM SHADE' },
  { icon: '☕', label: 'CUTTING CHAI' },
  { icon: '🏄‍♂️', label: 'SURFBOARD' },
  { icon: '🚀', label: 'SHIP FAST' },
  { icon: '🕶️', label: 'SHADES' },
];

export const DEFAULT_BADGE: BuilderBadgeData = {
  fullName: 'AMIT KUMAR',
  role: 'SOFTWARE DEVELOPMENT',
  builderClass: 'TERMINAL WIZARD',
  shipping: 'BUILDING THE FUTURE',
  builderId: '#HH-GOA-9884',
  beachBag: [
    { icon: '🥥', label: 'COCONUT' },
    { icon: '🛺', label: 'AUTO RICKSHAW' },
    { icon: '🎧', label: 'LO-FI BEATS' },
  ],
  socialHandle: '@247pmstudio',
  avatarUrl: '/zoro.png',
  avatarScale: 1.2,
  avatarOffsetX: 0,
  avatarOffsetY: -5,
  avatarFilter: 'normal',
  template: 'glass',
  accentColor: '#FF007A',
  bounty: '36,000',
};

export const PRESET_BUILDERS: (BuilderBadgeData & { name: string; title: string })[] = [
  {
    // ── One Piece Wanted Poster ── uses /luffy.jpg from public
    name: 'Monkey D. Luffy',
    title: 'Pirate King of Code',
    fullName: 'MONKEY D. LUFFY',
    role: 'WEB3 & PROTOCOLS',
    builderClass: 'PROTOCOL HACKER',
    shipping: 'FINDING ONE PIECE',
    builderId: '#HH-GOA-0001',
    beachBag: [
      { icon: '🏴‍☠️', label: 'JOLLY ROGER' },
      { icon: '🥩', label: 'MEAT' },
      { icon: '🚀', label: 'SHIP FAST' },
    ],
    socialHandle: '@hhgoa',
    avatarUrl: '/luffy.jpg',
    avatarScale: 1.1,
    avatarOffsetX: 0,
    avatarOffsetY: -10,
    avatarFilter: 'normal',
    template: 'glass',
    accentColor: '#E9C67C',
    bounty: '3,000,000,000',
  },
  {
    // ── Konkan Express ── uses /zoro.png from public
    name: 'Roronoa Zoro',
    title: 'Swordsman of Stack',
    fullName: 'RORONOA ZORO',
    role: 'SYSTEMS ENGINEERING',
    builderClass: 'KERNEL ARCHITECT',
    shipping: 'THREE SWORD STYLE API',
    builderId: '#HH-GOA-0002',
    beachBag: [
      { icon: '⚔️', label: 'THREE SWORDS' },
      { icon: '🚂', label: 'TRAIN PASS' },
      { icon: '☕', label: 'CUTTING CHAI' },
    ],
    socialHandle: '@hhgoa',
    avatarUrl: '/zoro.png',
    avatarScale: 1.2,
    avatarOffsetX: 0,
    avatarOffsetY: -5,
    avatarFilter: 'normal',
    template: 'train',
    accentColor: '#991B1B',
  },
  {
    // ── Retro Stamp ── uses Unsplash
    name: 'Priya Sharma',
    title: 'AI Sorceress',
    fullName: 'PRIYA SHARMA',
    role: 'AI & MACHINE LEARNING',
    builderClass: 'AI RESEARCHER',
    shipping: 'MULTIMODAL LLM AGENTS',
    builderId: '#HH-GOA-0003',
    beachBag: [
      { icon: '🧠', label: 'NEURAL NETS' },
      { icon: '🌴', label: 'PALM SHADE' },
      { icon: '🎧', label: 'LO-FI BEATS' },
    ],
    socialHandle: '@hhgoa',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800',
    avatarScale: 1,
    avatarOffsetX: 0,
    avatarOffsetY: 0,
    avatarFilter: 'normal',
    template: 'retro',
    accentColor: '#FF007A',
  },
  {
    // ── Dark Poster ── uses Unsplash
    name: 'Dev Mehta',
    title: 'Fullstack Ninja',
    fullName: 'DEV MEHTA',
    role: 'SOFTWARE DEVELOPMENT',
    builderClass: 'FULLSTACK NINJA',
    shipping: 'NEXT.JS 15 + RUST API',
    builderId: '#HH-GOA-0004',
    beachBag: [
      { icon: '💻', label: 'VS CODE' },
      { icon: '🥥', label: 'COCONUT' },
      { icon: '🏄‍♂️', label: 'SURFBOARD' },
    ],
    socialHandle: '@hhgoa',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=800',
    avatarScale: 1,
    avatarOffsetX: 0,
    avatarOffsetY: 0,
    avatarFilter: 'normal',
    template: 'dark',
    accentColor: '#FFE500',
  },
];
