import type { BuilderBadgeData } from '../types';

export const BUILDER_CLASSES = [
  'TERMINAL WIZARD',
  'PROMPT ENGINEER',
  'BYTE SORCERER',
  'CODE ALCHEMIST',
  'KERNEL ARCHITECT',
  'PIXEL ARTISAN',
  'FULLSTACK NINJA',
  'AI RESEARCHER',
  'CYBER DECKER',
  'PROTOCOL HACKER',
];

export const ROLES = [
  'SOFTWARE DEVELOPMENT',
  'AI & MACHINE LEARNING',
  'WEB3 & PROTOCOLS',
  'CREATIVE DIRECTION',
  'SYSTEMS ENGINEERING',
  'UI/UX ARCHITECTURE',
  'GAME DEVELOPMENT',
  'DATA SCIENCE',
];

export const BEACH_ITEMS_PRESETS = [
  { icon: '🥥', label: 'COCONUT' },
  { icon: '🛺', label: 'AUTO RICKSHAW' },
  { icon: '🚂', label: 'TRAIN PASS' },
  { icon: '💻', label: 'VS CODE' },
  { icon: '🎧', label: 'LO-FI BEATS' },
  { icon: '🌴', label: 'PALM SHADE' },
  { icon: '☕', label: 'CUTTING CHAI' },
  { icon: '🏄‍♂️', label: 'SURFBOARD' },
  { icon: '🚀', label: 'SHIP FAST' },
  { icon: '🕶️', label: 'SHADES' },
];

export const DEFAULT_BADGE: BuilderBadgeData = {
  fullName: 'AMIT KUMAR',
  role: 'SOFTWARE DEVELOPMENT',
  builderClass: 'TERMINAL WIZARD',
  shipping: 'BUILDING THE FUTURE',
  builderId: '#HH-GOA-9884',
  beachBag: [
    { icon: '🥥', label: 'COCONUT' },
    { icon: '🛺', label: 'AUTO RICKSHAW' },
    { icon: '🎧', label: 'LO-FI BEATS' },
  ],
  socialHandle: '@247pmstudio',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800',
  avatarScale: 1,
  avatarOffsetX: 0,
  avatarOffsetY: 0,
  avatarFilter: 'normal',
  template: 'retro',
  accentColor: '#FF007A',
};

export const PRESET_BUILDERS: (BuilderBadgeData & { name: string; title: string })[] = [
  {
    name: 'Amit Kumar',
    title: 'Terminal Wizard',
    ...DEFAULT_BADGE,
    fullName: 'AMIT KUMAR',
    builderClass: 'TERMINAL WIZARD',
    shipping: 'BUILDING THE FUTURE',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=800',
  },
  {
    name: 'Vasco Express',
    title: 'Konkan Rail Hacker',
    fullName: 'VASCO MAO',
    role: 'SOFTWARE DEVELOPMENT',
    builderClass: 'FULLSTACK NINJA',
    shipping: 'KONKAN TRAIN HACK',
    builderId: '#HH-GOA-1206',
    beachBag: [
      { icon: '🚂', label: 'TRAIN PASS' },
      { icon: '🛺', label: 'AUTO RICKSHAW' },
      { icon: '☕', label: 'CUTTING CHAI' },
    ],
    socialHandle: '@hhgoa',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=800',
    avatarScale: 1,
    avatarOffsetX: 0,
    avatarOffsetY: 0,
    avatarFilter: 'normal',
    template: 'train',
    accentColor: '#991B1B',
  },
  {
    name: 'Sam Altman',
    title: 'AGI Architect',
    fullName: 'SAM ALTMAN',
    role: 'AI & MACHINE LEARNING',
    builderClass: 'PROMPT ENGINEER',
    shipping: 'GPT-5 & BEYOND',
    builderId: '#HH-GOA-0001',
    beachBag: [
      { icon: '🧠', label: 'NEURAL NETS' },
      { icon: '💻', label: 'MACBOOK' },
      { icon: '⚡', label: 'COMPUTE' },
    ],
    socialHandle: '@sama',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800',
    avatarScale: 1,
    avatarOffsetX: 0,
    avatarOffsetY: 0,
    avatarFilter: 'normal',
    template: 'retro',
    accentColor: '#FF007A',
  },
  {
    name: 'Linus Torvalds',
    title: 'Kernel Legend',
    fullName: 'LINUS TORVALDS',
    role: 'SYSTEMS ENGINEERING',
    builderClass: 'KERNEL ARCHITECT',
    shipping: 'LINUX 6.12 & GIT',
    builderId: '#HH-GOA-0000',
    beachBag: [
      { icon: '🐧', label: 'TUX PENGUIN' },
      { icon: '☕', label: 'DARK ROAST' },
      { icon: '⌨️', label: 'VIM' },
    ],
    socialHandle: '@torvalds',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=800',
    avatarScale: 1,
    avatarOffsetX: 0,
    avatarOffsetY: 0,
    avatarFilter: 'vintage',
    template: 'dark',
    accentColor: '#FFE500',
  },
];
